### ISSUE TITLE
[Suggestion] Blacklist option?

### ISSUE THREAD

**Issue by xJon** [GTNewHorizons/NotEnoughItems#369]
Would be particularly useful for instances like https://github.com/FlansMods/FlansMod/issues/647

<details>
  <summary>Example</summary>

![image](https://user-images.githubusercontent.com/8945347/230987576-9d50641e-8ef1-472b-b6e4-7dc4131b32fe.png)

```
[22:57:09] [Client thread/INFO]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:460]: Error while rendering: 1xtile.flansWorkbench@4
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraft.util.ReportedException: Rendering item
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:604)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:258)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:240)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:236)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:232)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.ItemsGrid.drawItem(ItemsGrid.java:339)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.ItemsGrid.drawItems(ItemsGrid.java:287)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.ItemsGrid.draw(ItemsGrid.java:328)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.PanelWidget.draw(PanelWidget.java:176)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:265)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:470)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4006)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.flansmod.common.BlockFlansWorkbench.func_149691_a(BlockFlansWorkbench.java:47)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.RenderBlocks.func_147787_a(RenderBlocks.java:8232)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8175)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
[22:57:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 23 more
[22:57:09] [Client thread/INFO]: [CHAT] There was error during rendering item. Please check log for details.
...
```

</details>

**Comment by xJon** [comment]
@slprime Implementing a `hiddenitems.cfg` is great, but would you also consider an option for hiding items in-game, similarly to JEI? It also helps visually grasping what you are hiding.
I believe the current method requires manually inserting the relevant item IDs into the config file.
