### ISSUE TITLE
Crash after exiting recipe viewer in my pack after version 2.3.15

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/NotEnoughItems#388]
Currently using 2.3.54 and I get this crash:

```
java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1058)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6005)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[crash-2023-06-05_06.30.42-client.txt](https://github.com/GTNewHorizons/NotEnoughItems/files/11648821/crash-2023-06-05_06.30.42-client.txt)

log:

[latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/11648822/latest.log)

**Comment by wlhlm** [comment]
This looks to me like you are hitting https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12658

**Comment by brandyyn** [comment]
this is in a fresh world and just in my inventory

CodeChickenCore-1.1.11

CodeChickenLib-1.7.10-1.1.8

**Comment by Denostrov** [comment]
fixed something similar related to forestry recently.
Gonna look into this later today

**Comment by Denostrov** [comment]
@brandyyn is your pack publicly available? I have no way of testing a potential fix otherwise

**Comment by brandyyn** [comment]
> @brandyyn is your pack publicly available? I have no way of testing a potential fix otherwise

happy to put my environment on technic launcher for u if that works?

**Comment by Denostrov** [comment]
> > @brandyyn is your pack publicly available? I have no way of testing a potential fix otherwise
> 
> happy to put my environment on technic launcher for u if that works?

yeah just need a way to launch the game and check

**Comment by brandyyn** [comment]
@Denostrov paste this into the technic launcher https://api.technicpack.net/modpack/void-rift

**Comment by Denostrov** [comment]
@brandyyn the linked pull request seems to have fixed it. Or at least i can't seem to reproduce the crash anymore

**Comment by Denostrov** [comment]
also can i just say your modpack is *fucked up* bruh
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/47501679/4aa74c57-ba19-4da8-97c1-2b8d1445bbc9)
