### ISSUE TITLE
Creative mode IndexOutOfBoundsException when using TrashSlot

### ISSUE THREAD

**Issue by Fatih120** [GTNewHorizons/NotEnoughItems#422]
When the [TrashSlot](https://www.curseforge.com/minecraft/mc-mods/trashslot) mod is installed and a recipe is viewed specifically within Creative mode, the game crashes and returns the following:

java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)...

This crash is very similar to the one visible here: https://github.com/GTNewHorizons/NotEnoughItems/issues/388
To reiterate, this crash does not happen when checking a recipe during Survival, and I have singled out TrashSlot as the only mod that causes this error.
I made sure to update the mod since I saw this: https://github.com/GTNewHorizons/Hodgepodge/pull/219 - but the case is still the same.

**Comment by Nilau1998** [comment]
The 3 lines of log you provide don't help at all, pos the full crash log for proper support

**Comment by awbarr** [comment]
I have the same issue. Attached is my version of the crash report using my own modpack. The source is definitely this mod and I am able to reproduce the issue.

https://pastebin.com/iuh1rGyV

**Comment by miozune** [comment]
Cannot reproduce with simple NEI + TrashSlot env, so another mod should be involved in this issue.
