### ISSUE TITLE
Item Loading Issue

### ISSUE THREAD

**Issue by Bennyboy1695** [GTNewHorizons/NotEnoughItems#426]
I replaced the nei version in the material energy ^4 pack with this one as i like the features and stuff of this one better than normal nei. But whn joining the world my items never loaded and this appeared in my log
```
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoSuchMethodError: extracells.integration.opencomputers.UpgradeItemAEBase$class.getRarity(Lextracells/integration/opencomputers/UpgradeItemAEBase;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/EnumRarity;
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at extracells.item.ItemOCUpgrade$.func_77613_e(ItemOCUpgrade.scala:8)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.enderio.core.common.transform.EnderCoreMethods.getItemRarity(EnderCoreMethods.java:42)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.item.ItemStack.func_77953_t(Unknown Source)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:155)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:232)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.api.ItemInfo.lambda$getSearchName$4(ItemInfo.java:523)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:520)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.api.ItemInfo.populateSearchMap(ItemInfo.java:170)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.ItemList$1.execute(ItemList.java:230)
[17:53:22] [NEI Item Loading/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:25)
```

Version: Latest on CF for this and dependencies

**Comment by miozune** [comment]
Are you sure this is solely caused by changing NEI version, without changing other mods?

**Comment by Bennyboy1695** [comment]
The only two mods I changed were the NEI version to be the GT latest version and the codechicken dependency to the latest too

**Comment by miozune** [comment]
Even though the same error appears in the log, I can still view item list and search names.
> my items never loaded

What do you mean by this?

**Comment by Bennyboy1695** [comment]
> What do you mean by this?
it just never progressed past the part where it says its getting the item list or whatever the exact phrase is
