### ISSUE TITLE
NPE caused by new "Concurrent recipe handler"

### ISSUE THREAD

**Issue by QartemisT** [GTNewHorizons/NotEnoughItems#479]
The commit <https://github.com/GTNewHorizons/NotEnoughItems/commit/5056fe5437f289d2e7ca7deb8dc6a803d85279f7> has caused a new NPE issue to occur.

Version 2.5.27 appears to not have this issue, however 2.6.0 and 2.5.28 do (where this commit got merged into).

```
java.lang.NullPointerException: Updating screen events
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1084)
	at codechicken.nei.util.AsyncTaskProfiler.end(AsyncTaskProfiler.java:24)
	at codechicken.nei.recipe.RecipeHandlerQuery.runWithProfiling(RecipeHandlerQuery.java:52)
	at codechicken.nei.recipe.GuiCraftingRecipe.getCraftingHandlers(GuiCraftingRecipe.java:108)
	at codechicken.nei.recipe.GuiCraftingRecipe.createRecipeGui(GuiCraftingRecipe.java:47)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:29)
	at codechicken.nei.PanelWidget.mouseUp(PanelWidget.java:336)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:237)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:481)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:474)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by LasmGratel** [comment]
What recipe are you viewing before the crash?

**Comment by Abalieno** [comment]
Can confirm a somewhat similar one:

```
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
    at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1089)
    at codechicken.nei.util.AsyncTaskProfiler.end(AsyncTaskProfiler.java:24)
    at codechicken.nei.recipe.RecipeHandlerQuery.runWithProfiling(RecipeHandlerQuery.java:52)
    at codechicken.nei.recipe.GuiCraftingRecipe.getCraftingHandlers(GuiCraftingRecipe.java:108)
    at codechicken.nei.recipe.GuiCraftingRecipe.createRecipeGui(GuiCraftingRecipe.java:47)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:29)
    at codechicken.nei.api.ShortcutInputHandler.handleKeyEvent(ShortcutInputHandler.java:79)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:15)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:429)
    at net.minecraft.client.gui.inventory.GuiContainer.keyTyped(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:652)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:639)
    at net.minecraft.client.gui.inventory.GuiContainer.handleKeyboardInput(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:276)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:973)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

**Comment by msparkles** [comment]
Happens to us as well. The issue is with any recipes it seems.
